application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

spring:
  data:
    mongodb:
      uri: "mongodb+srv://virtualtravelassistance:6PaQ97vi0uYkV7TG@vta.i7fwmes.mongodb.net/vtaDatabase?retryWrites=true&w=majority&appName=VTA"

server:
  port: 5000