springbootwebfluxjjwt:
    jjwt:
      secret: CHANGE_ME_ENCODER_ABCDEFGHIJKLMNOP
      expiration: 172800
    password:
      encoder:
        secret: CHANGE_ME_ENCODER_ABCDEFGHIJKLMNOP
        iteration: 33
        keylength: 256
spring:
  data:
    mongodb:
      uri: "mongodb+srv://virtualtravelassistance:6PaQ97vi0uYkV7TG@vta.i7fwmes.mongodb.net/vtaDatabase?retryWrites=true&w=majority&appName=VTA"

server:
  port: 5000