application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://virtualtravelassistance:6PaQ97vi0uYkV7TG@vta.i7fwmes.mongodb.net/vtaDatabase?retryWrites=true&w=majority&appName=VTA}

server:
  port: ${SERVER_PORT:5000}
