springbootwebfluxjjwt:
  jjwt:
    secret: ASADASKJDAKSJDAJSDKJSAJDJASFIQEQ#EQ@#SADASDASDAS
    expiration: 172800
  password:
    encoder:
      secret: CHANGE_ME_ENCODER
      iteration: 33
      keylength: 256

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      auto-index-creation: false
      database: authtemplate
